name: JIT

on: push
https://github.com/ossia/score/releases/download/v${{ matrix.version }}/ossia.score-3.0.0-a36-
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [ 3.0.0-a36 ]
        config:
          - {
              name: "Windows",
              os: windows-latest,
              score: "win64.exe",
              sdk: windows-sdk.zip
            }
          - {
              name: "Ubuntu",
              os: ubuntu-latest,
              score: "linux-amd64.AppImage",
              sdk: linux-sdk.zip
            }
          - {
              name: "macOS",
              os: macos-latest,
              score: "macOS.dmg",
              sdk: mac-sdk.zip
            }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Download score
        shell: bash
        run: |
          SCORE_FILENAME=ossia.score-${{ matrix.version }}-${{ matrix.config.score }}
          curl -L -O "https://github.com/ossia/score/releases/download/v${{ matrix.version }}/$SCORE_FILENAME"

      - name: Download SDK
        shell: bash
        run: |
          SDK_FILENAME=${{ matrix.sdk }}
          curl -L -O "https://github.com/ossia/score/releases/download/v${{ matrix.version }}/$SDK_FILENAME"
          mkdir -p "$HOME/Documents/ossia score library/SDK"
          unzip -qq "$SDK_FILENAME" -d "$HOME/Documents/ossia score library/SDK/${{ matrix.version }}"
