name: JIT

on: push

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [3.0.0-a37]
        config:
          - {
              name: "Windows",
              os: windows-latest,
              score: "win64.exe",
              sdk: windows-sdk.zip,
            }
          - {
              name: "Ubuntu",
              os: ubuntu-latest,
              score: "linux-amd64.AppImage",
              sdk: linux-sdk.zip,
            }
          - {
              name: "macOS",
              os: macos-latest,
              score: "macOS.dmg",
              sdk: mac-sdk.zip,
            }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Download score
        shell: bash
        run: |
          SCORE_FILENAME=ossia.score-${{ matrix.version }}-${{ matrix.config.score }}
          curl -L -O "https://github.com/ossia/score/releases/download/v${{ matrix.version }}/$SCORE_FILENAME"

      - name: Install score
        if: matrix.config.name == 'macOS'
        shell: bash
        run: |
          SCORE_FILENAME=ossia.score-${{ matrix.version }}-${{ matrix.config.score }}
          /usr/bin/hdiutil convert -quiet $SCORE_FILENAME -format UDTO -o score
          /usr/bin/hdiutil attach -quiet -nobrowse -noverify -noautoopen -mountpoint /Volumes/score score.cdr
          ls /Volumes
          ls /Volumes/score

      - name: Install score
        if: matrix.config.name == 'Windows'
        shell: bash
        run: |
          SCORE_FILENAME=ossia.score-${{ matrix.version }}-${{ matrix.config.score }}
          7z x $SCORE_FILENAME

      - name: Download SDK
        shell: bash
        run: |
          SDK_FILENAME=${{ matrix.config.sdk }}
          curl -L -O "https://github.com/ossia/score/releases/download/v${{ matrix.version }}/$SDK_FILENAME"
          mkdir -p "$HOME/Documents/ossia score library/SDK"
          unzip -qq "$SDK_FILENAME" -d "$HOME/Documents/ossia score library/SDK/${{ matrix.version }}"

      - name: Compile
        if: matrix.config.name == 'macOS'
        shell: bash
        run: |
          SCORE_FILENAME=/Volumes/score/score.app/Contents/MacOS/score
          $SCORE_FILENAME --no-gui --compile-addon $PWD

      - name: Compile
        if: matrix.config.name == 'Windows'
        shell: bash
        run: |
          SCORE_FILENAME=score.exe
          ./$SCORE_FILENAME --no-gui --compile-addon $PWD

      - name: Compile
        if: matrix.config.name == 'Ubuntu'
        shell: bash
        run: |
          sudo apt -y install libasound2 libxcb1 libglvnd0 libx11-6 libxcb-glx0 libgl1 libdbus-1-3 libxcb-xkb1 libxkbcommon-x11-0 libxcb-xkb1
          SCORE_FILENAME=ossia.score-${{ matrix.version }}-${{ matrix.config.score }}
          chmod +x $SCORE_FILENAME
          ./$SCORE_FILENAME --no-gui --compile-addon $PWD
